class GrayOMError(Exception):
    def __init__(
        self, user_message: str, *, technical_message: str | None = None,
        recoverable: bool = True, suggested_action: str = "Run: grayom doctor",
    ) -> None:
        super().__init__(technical_message or user_message)
        self.user_message = user_message
        self.technical_message = technical_message or user_message
        self.recoverable = recoverable
        self.suggested_action = suggested_action


class DetectionError(GrayOMError): ...
class ConfigurationError(GrayOMError): ...
class CompatibilityError(GrayOMError): ...
class SourceError(GrayOMError): ...
class InstallationError(GrayOMError): ...
class HealthCheckError(GrayOMError): ...
class RollbackError(GrayOMError): ...
